### ISSUE TITLE
Issues with the plugin on GOLand

### ISSUE THREAD

**Issue by camdenorrb** [symflower/symflower#15]
Getting the following error:
`error: could not import fmt (go/build: go list fmt: exec: "go": executable file not found in $PATH`

I've checked the PATH on bash and zshrc both seem to be fine with the `go` command found, even installed GO through homebrew and double checked the goroot in goland preferences

Anyone else experiencing this or have any ideas?

**Comment by evan-mcclaugherty** [comment]
Same issue here.

**Comment by zimmski** [comment]
Thanks for reporting this!

@camdenorrb @evan-mcclaugherty This is a bug, but we need to reproduce your setup. Can you please post your GoLand versions and the output of `symflower version`. The binary is inside the "share" directory of the extension's directory. I usually find it by doing the following command `find ~ | grep share/symflower` (which gives me "/home/zimmski/.local/share/JetBrains/IdeaIC2022.2/Symflower (beta)/share/symflower")

**Comment by camdenorrb** [comment]
@zimmski thank you for the fast response.

Goland version: 2022.2.2

 symflower v25003 on darwin/arm64
 
 BuildVersion: 21G83
 KernelVersion: 21.6.0
 ProductName: macOS
 ProductVersion: 12.5.1

**Comment by evan-mcclaugherty** [comment]
when i update symflower i get these two errors:

java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at com.symflower.activity.ExtensionStartupActivity.runActivity(ExtensionStartupActivity.java:33)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:247)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:650)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:246)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:241)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:189)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$sam$java_lang_Runnable$0.run(StartupManagerImpl.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1.run(trace.kt:90)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.symflower.languageserver.LSWrapper.startServer(LSWrapper.java:101)
	at com.symflower.activity.ExtensionStartupActivity.runActivity(ExtensionStartupActivity.java:31)
	... 31 more
Caused by: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at jdk.proxy8/jdk.proxy8.$Proxy182.initialize(Unknown Source)
	at com.symflower.languageserver.LSWrapper.startServer(LSWrapper.java:99)
	... 32 more
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 36 more
	
	and
	
	java.lang.RuntimeException: java.lang.Exception: Language server already running.
	at com.symflower.activity.ExtensionStartupActivity.runActivity(ExtensionStartupActivity.java:33)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:247)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:650)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:246)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:241)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:189)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$sam$java_lang_Runnable$0.run(StartupManagerImpl.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1.run(trace.kt:90)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.Exception: Language server already running.
	at com.symflower.languageserver.LSWrapper.startServer(LSWrapper.java:52)
	at com.symflower.activity.ExtensionStartupActivity.runActivity(ExtensionStartupActivity.java:31)
	... 31 more

**Comment by loves-bruins** [comment]
Has this been fixed?  I to am getting same errors with Goland 2022.3.1

`Initializing language server
symflower v27903 on darwin/arm64

BuildVersion: 21G419
KernelVersion: 21.6.0
PATH: /Users/lrogers/Library/Application Support/JetBrains/GoLand2022.3/plugins/Symflower/share/install/bin:/usr/bin:/bin:/usr/sbin:/sbin
ProductName: macOS
ProductVersion: 12.6.3
Handling request(1, "initialize")
Acceptable workspace: event-data-validator (/Users/lrogers/dev/b2/b2cm/event-data-validator/)
Responding to request(1, "initialize")
Handling request(2, "symflower/unit-test")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd1, 0xd5, 0x13, 0x86, 0xb6, 0xc3, 0x11, 0xed, 0xb0, 0x35, 0xde, 0x78, 0x55, 0x98, 0x52, 0x29}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /Users/lrogers/dev/b2/b2cm/event-data-validator/
Search for Go files
Load dependency stdlib:@dev
internal/schema/validator.go:24:13: error: undeclared name: jsonschema
internal/schema/validator.go:33:28: error: undeclared name: jsonschema
internal/schema/validator.go:33:50: error: undeclared name: jsonschema
internal/schema/validator.go:65:28: error: undeclared name: jsonschema
internal/schema/validator.go:82:33: error: undeclared name: jsonschema
internal/schema/validator.go:98:38: error: undeclared name: jsonschema
internal/schema/validator.go:59:14: error: undeclared name: jsonschema
internal/schema/validator.go:60:19: error: undeclared name: jsonschema
internal/schema/validator.go:16:2: error: could not import encoding/json (cannot find package "encoding/json" in any of:
		($GOROOT not set)
		/Users/lrogers/dev/b2/b2cm/event-data-validator/src/encoding/json (from $GOPATH))
internal/schema/validator.go:17:2: error: could not import event-data-validator/config (cannot find package "event-data-validator/config" in any of:
		($GOROOT not set)
		/Users/lrogers/dev/b2/b2cm/event-data-validator/src/event-data-validator/config (from $GOPATH))
internal/schema/validator.go:18:2: error: could not import fmt (cannot find package "fmt" in any of:
		($GOROOT not set)
		/Users/lrogers/dev/b2/b2cm/event-data-validator/src/fmt (from $GOPATH))
internal/schema/validator.go:19:2: error: could not import path (cannot find package "path" in any of:
		($GOROOT not set)
		/Users/lrogers/dev/b2/b2cm/event-data-validator/src/path (from $GOPATH))
internal/schema/validator.go:21:2: error: could not import github.com/santhosh-tekuri/jsonschema/v5 (cannot find package "github.com/santhosh-tekuri/jsonschema/v5" in any of:
		($GOROOT not set)
		/Users/lrogers/dev/b2/b2cm/event-data-validator/src/github.com/santhosh-tekuri/jsonschema/v5 (from $GOPATH))
Found 1 Go files
Found 13 problems in Go files
internal/schema/validator.go: found 0 symbols
Sending notification(method: window/showMessage, data: lsp.ShowMessageParams{Type:0x1, Message:"Unknown error. Please check the Symflower log for more details."})
Responding to request(2, "symflower/unit-test")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd1, 0xd5, 0x13, 0x86, 0xb6, 0xc3, 0x11, 0xed, 0xb0, 0x35, 0xde, 0x78, 0x55, 0x98, 0x52, 0x29}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
`
